package com.traccy.dgmn.config.constant;

public interface ResponseMessageConstants {
  //SYSTEM
  String SUCCESS = "MSG_SUCCESS";
  String ERROR = "MSG_ERROR";
  String ACCESS_DENIED = "MSG_ACCESS_DENIED";

  //COMMON
  String DATA_INVALID = "MSG_DATA_INVALID";

  //PRODUCT
  String CREATE_PRODUCT_SUCCESS = "MSG_CREATE_PRODUCT_SUCCESS";
  String CREATE_PRODUCT_FAIL = "MSG_CREATE_PRODUCT_FAIL";
  String PRODUCT_EXIST = "MSG_PRODUCT_EXIST";
  String PRODUCT_NAME_NOT_BLANK = "MSG_PRODUCT_NAME_NOT_BLANK";

  //IMAGE
  String UPLOAD_AVATAR = "MSG_CHOOSE_IMAGE_FOR_PRODUCT";

  //CATEGORY
  String CATEGORY_NOT_EXIST = "MSG_PRODUCT_TYPE_NOT_EXIST";
  String CATEGORY_EXIST = "MSG_CATEGORY_EXIST";
  String CREATE_CATEGORY_SUCCESS = "MSG_CREATE_CATEGORY_SUCCESS";
  String CREATE_CATEGORY_FAIL = "MSG_CREATE_CATEGORY_FAIL";
  String CATEGORY_NAME_NOT_BLANK = "MSG_CATEGORY_NAME_NOT_BLANK";

  //UNIT
  String UNIT_NOT_EXIST = "MSG_UNIT_NOT_EXIST";
}
