package com.traccy.dgmn.config.constant;

public interface ResponseMessageConstants {
  //SYSTEM
  String SUCCESS = "MSG_SUCCESS";
  String ERROR = "MSG_ERROR";
  String ACCESS_DENIED = "MSG_ACCESS_DENIED";

  //COMMON
  String DATA_INVALID = "MSG_DATA_INVALID";

  //PRODUCT
  String CREATE_PRODUCT_SUCCESS = "MSG_CREATE_PRODUCT_SUCCESS";
  String CREATE_PRODUCT_FAIL = "MSG_CREATE_PRODUCT_FAIL";
  String PRODUCT_EXIST = "MSG_PRODUCT_EXIST";
  String PRODUCT_NOT_EXIST = "MSG_PRODUCT_NOT_EXIST";
  String PRODUCT_NAME_NOT_BLANK = "MSG_PRODUCT_NAME_NOT_BLANK";
  String PRICE_GREATER_THAN_0 = "MSG_PRICE_GREATER_THAN_0";

  //IMAGE
  String UPLOAD_AVATAR = "MSG_CHOOSE_IMAGE_FOR_PRODUCT";
  String CANNOT_SAVE_IMAGE = "MSG_CANNOT_SAVE_IMAGE";
  String IMAGE_QUANTITY_LIMIT = "MSG_IMAGE_QUANTITY_LIMIT_IS_5";

  //CATEGORY
  String CATEGORY_NOT_EXIST = "MSG_CATEGORY_NOT_EXIST";
  String CATEGORY_EXIST = "MSG_CATEGORY_EXIST";
  String CREATE_CATEGORY_SUCCESS = "MSG_CREATE_CATEGORY_SUCCESS";
  String CREATE_CATEGORY_FAIL = "MSG_CREATE_CATEGORY_FAIL";
  String CATEGORY_NAME_NOT_BLANK = "MSG_CATEGORY_NAME_NOT_BLANK";

  //UNIT
  String UNIT_NOT_EXIST = "MSG_UNIT_NOT_EXIST";
  String UNIT_EXIST = "MSG_UNIT_EXIST";
  String UNIT_NAME_NOT_BLANK = "MSG_UNIT_NAME_NOT_BLANK";

  //SHOP INFORMATION
  String SHOP_INFORMATION_NOT_EXIST = "MSG_SHOP_INFORMATION_NOT_EXIST";
  String FIELD_NOT_BLANK = "MSG_FIELD_NOT_BLANK";
  String CREATE_SHOP_INFORMATION_SUCCESS = "MSG_CREATE_SHOP_INFORMATION_SUCCESS";
  String SHOP_INFORMATION_QUANTITY_LIMIT = "MSG_SHOP_INFORMATION_QUANTITY_LIMIT_IS_5";
}
